route:
  receiver: emailer
receivers:
  - name: emailer
    email_configs:
      - to: <your mail account>
        from: <your mail account>
        smarthost: smtp.gmail.com:587
        auth_username: <your mail account>
        auth_identity: <your mail account>
        auth_password: